### ISSUE TITLE
3D Graphics cards

### ISSUE THREAD

**Issue by Torinde** [joncampbell123/dosbox-x#5040]
### Is your feature request related to a problem? Please describe.

Sharing here the list of 3D chips that aren't emulated yet. Continuation of:
- #4139

Number of games per 3D proprietary game APIs: [Vogons forum](https://www.vogons.org/viewtopic.php?f=63&t=33483), [Vogons wiki](https://www.vogonswiki.com/index.php/Graphics_Cards), [TTLG](https://www.ttlg.com/forums/showthread.php?t=98258), [DOS_TESTS](http://gona.mactar.hu/DOS_TESTS/), [3D Graphics Cards / Accelerators Supported](https://www.mobygames.com/attributes/tech-specs/18/)

### What you want

Sorted by total number of games (exclusive + supported):
- [ ] PowerSGL (Ultim@te Race, the original Tomb Raider) - 12 exclusive games + 31 supported games + 12 wrapper games + more? - Dreamcast emulators, [PowerVR-Series1](https://github.com/powervr-graphics/PowerVR-Series1); #291
- [ ] Rendition Speedy3D/RRedline (Descent II, Grand Prix Legends, IndyCar Racing II, the Myth games, Sierra's NASCAR, Quake, Quake II, EF2000 V2.0, and Tomb Raider) - 2 exclusive games + 24 supported games; #5802; [RReady wrapper](https://nirvtek.com/rready.php)
- [ ] S3D ViRGE - [S3D](https://www.vogonswiki.com/index.php/S3): 5 exclusive games + 14 supported games; #167
- [ ] ATI 3D Rage (ATI CIF) - 1 exclusive game + 13 supported games, Rage Pro is the last chip to support ATI's CIF (and also Win3x), [glrage](https://github.com/ata4/glrage), [dingusppc](https://github.com/dingusdev/dingusppc/blob/master/devices/video/atirage.cpp); #3058
- [ ] 3D Blaster (CGL) - 3Dlabs - 3 exclusive games + 10 supported games; #291
- [ ] Matrox Mystique (MSI) - 2 exclusive games + 10 supported games - 86box emulates it
- [ ] Nvidia NV1/2 (GPU+sound) - 4 exclusive games + 3 supported games; #1773
- [ ] Matrox Impression Plus (RenderWare 3D) - 4 exclusive games; #291
- [ ] Paradise Tasmania 3D (RenderWare, BRender and RenderMorphics) - WD/Philips/Yamaha - 2 exclusive games; #291
- [ ] S3 [Savage](https://www.vogonswiki.com/index.php/S3) MeTaL/S3TC - MeTaL: Deus Ex, Unreal Tournament; #1773
- [ ] Matrox G400 - 2 supported games - Environment Mapped Bump Mapping (EMBM) - Matrox G400, Radeon 7200, possible also as DX8 implementation - used in few games such as Dungeon Keeper 2 and Millennium Soldier: Expendable - [qemu-3dfx "Runtime-patch" engine](https://www.reddit.com/r/86box/comments/1ffo8o2/comment/lnn5aeu/)
- [ ] Matrox Millennium - 1 supported game - 86box emulates it
- [ ] PC-FX GA - "Unlike PC-9800 variant, this [DOS/V variant](https://youtu.be/JM04vH2et5A) uses a single ISA card and both variants integrate an additional 3D chipset (Kubota/Hudson HuC6273) over the regular PC-FX video game console"
- [ ] 3DLabs GLINT, Permedia1/2/3 - it seems those are OpenGL and Autodesk [HEIDI](https://www.scriptspot.com/bobo/rendfaq/RFAQ0080.HTM), have separate game lists [here](https://www.mobygames.com/attributes/tech-specs/18/)

3D DirectX/OpenGL - [DX1-8-on-9](https://github.com/elishacloud/dxwrapper) 
- [ ] Riva128 (DX5) -  [aquaboxs/dosbox-x](https://github.com/aquaboxs/dosbox-x); #1773, #3412
- [ ] Voodoo3 (DX6) -  [aquaboxs/dosbox-x](https://github.com/aquaboxs/dosbox-x); #1773; 86box emulates it
- [ ] Voodoo4/5 (DX6) - [86Box](https://github.com/86Box/86Box/discussions/2909)
- [ ] Rage 128/XL (DX6) - [QEMU](https://www.kraxel.org/blog/2019/09/display-devices-in-qemu/) "ati vga" has model=rage128p selects the "Rage 128 Pro" and model=rv100 selects the "Radeon RV100" (DX7). "Most important 2D accel ops are implemented too. 3D acceleration is not implemented yet."; #3889, https://github.com/86Box/86Box/pull/4926
- [ ] SoftGPU DX6/7/8/9 
  - [ ] currently [requires](https://github.com/JHRobotics/vmdisp9x?tab=readme-ov-file#vmdisp9x) one of the following: 
    - [ ] Bochs VBE Extensions (Bochs: VBE, VirtulBox: VboxVGA, QEMU: std-vga)
    - [ ] HW3D: VMWare SVGA-II (VMWare Workstation/Player, VirtulBox: VMSVGA, QEMU: vmware-svga, std-vga + [3dfx](https://github.com/kjliew/qemu-3dfx)) #3405
    - [ ] HW3D: VBox SVGA (VirtulBox: VBoxSVGA)
  - [ ] [can be developed](https://github.com/JHRobotics/softgpu/issues/13#issuecomment-1628424754) to support [QEMU virtio](https://www.kraxel.org/blog/2019/09/display-devices-in-qemu/).
  - [ ] [can be developed](https://github.com/JHRobotics/softgpu/issues/22) to support an already emulated device (even if emulation is only 2D so far; requires open source driver?) and the DirectX level depends on the DDI of that device (DX7 runs on any device driver interface/DDI, DX8 on DDI6+, DX9 on DDI7+)
    - [ ] DX8 base driver from emulation of Nvidia, ATI, Intel, S3/VIA, PowerVR, SiS, Trident, 3DLabs, Matrox
    - [ ] DX9 base driver from emulation of Nvidia, ATI, Intel, S3/VIA, PowerVR, SiS/XGI, 3DLabs

### Have you checked that no similar feature request(s) exist?

- [X] I have searched and didn't find any similar feature request.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by BridgeHeadland** [comment]
@Torinde If there's anything DOSBox-X should be able to emulate, it's ATI 3D, but because Windows XP can run in DOSBox-X, it should one day also be able to run ATI 3D Rage Pro, ATI Rage XC and ATI Rage XL in general, which are the only graphics cards from ATI that WXP supports. Personally, I'm not familiar with XC and XL, which is why I don't know the difference.
<img width="960" alt="ATI1" src="https://github.com/joncampbell123/dosbox-x/assets/85258509/96f02405-d09e-4ddc-9c0a-1c9e9d91bbcf">
<img width="960" alt="ATI2" src="https://github.com/joncampbell123/dosbox-x/assets/85258509/deafc2d8-4578-4ac2-ac55-03b9bd50ecdf">
<img width="960" alt="ATI3" src="https://github.com/joncampbell123/dosbox-x/assets/85258509/b0c272c2-4fa8-4fb9-9373-78c831465e96">
It's the first time I upload screenshots of WXP in 1920x1440 resolution, it's because I now understand how to use the advanced option in the configuration.
